version: 2

jobs:
  build:

    docker:
      - image: circleci/node:12-browsers

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "src/package.json" }}
      - run: cd src && npm i --silent
      - save_cache:
          key: dependency-cache-{{ checksum "src/package.json" }}
          paths:
            - src/node_modules
      - run: cd src && npm run build
